- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
- name: wr to file
  hosts: all
  tasks:
    - name: write to file
      command: sleep 20 
    - name: write to file
      command: date
      register: DATE
    - name: write to file
      copy: content="{{ DATE }}" dest=qq.txt
    - name: read file
      command: cat qq.txt
