- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
- name: wr to file
  hosts: all
  tasks:
    - name: sleep
      command: sleep 20 
    - name: get date
      command: date
      register: DATE
    - name: write to file
      #lineinfile:
        #path: "{{playbook_dir}}/qq.txt"
        #line: "{{ DATE.stdout }}"
        #insertbefore: BOF
      copy: content="{{ DATE.stdout }}" dest="{{playbook_dir}}/qq.txt"
    - name: read file
      command: cat qq.txt
      register: text
    - name: print file
      debug:
        msg: "{{text.stdout}}"
    - name: pwd
      command: pwd
      register: pwd
    - debug:
        msg: "{{pwd.stdout}}"
    - name: ls
      command: ls
      register: ls
    - debug:
        msg: "{{ls.stdout}}"
