- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
- name: wr to file
  hosts: all
  tasks:
    - name: sleep
      command: sleep 20 
    - name: get date
      command: date
      register: DATE
    - name: write to file
      copy: content="{{ DATE }}" dest="{{playbook_dir}}/qq.txt"
    - name: read file
      command: cat qq.txt
      register: text
    - name: print file
      debug:
        msg: "{{text.stdout}}"
    - name: pwd
      command: pwd
    - name: ls
      command: ls
